general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]

TERM = "xterm-256color"

[font]

size = 14.0

normal = { family = "MesloLGM Nerd Font Mono" }

[window]

padding = { x = 8, y = 8 }

dynamic_title = true

option_as_alt = "Both"

[keyboard]

bindings = [
  { key = "Left",   mods = "Alt",     chars = "\u001BB"       },
  { key = "Right",  mods = "Alt",     chars = "\u001BF"       },
  { key = "Left",   mods = "Command", chars = "\u001bOH"      },
  { key = "Right",  mods = "Command", chars = "\u001bOF"      },
  { key = "Back",   mods = "Alt",     chars = "\u001b\u007f"  },
  { key = "Back",   mods = "Command", chars = "\u0015"        },
]

